version: "3"
services:
  nexus:
  container_name: nexus-oss-repo
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "8085:8085"
    deploy:
      resources:
#        limits:
#          cpus: '0.001'
#          memory: 50M
        reservations:
          cpus: '1'
          memory: 200M
volumes:
  nexus-data: {}


